n = input("digite algo: ")
print(type(n))
print("é alfa númerico?",  n.isalnum())
print("é um número? ", n.isnumeric())
print("é uma palavra? ", n.isalpha())
print("é um decimal? ", n.isdecimal())
print("só tem espaços? ", n.isspace())
print("está capitalizada? ", n.istitle())
print("é escrito em letras maiusculas?", n.isupper())
print("é escrito em letras minusculas?", n.islower())
print("Isso era o que precisavamos de {} obrigada!".format(n))